# Generated by Django 2.2.4 on 2019-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('organisation', models.CharField(max_length=250, verbose_name='Organization / Institution')),
                ('address', models.TextField()),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
