# Generated by Django 2.2.4 on 2019-08-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('organisation', models.CharField(max_length=250, verbose_name='Organization / Institution')),
                ('department', models.CharField(max_length=250, verbose_name='Department')),
                ('cname', models.CharField(default='International Seminar on Refugees Welfare Policies and the State', max_length=250, verbose_name='Conference Name')),
                ('ccity', models.CharField(default='Trivandrum', max_length=250, verbose_name='Conference City')),
                ('comments', models.TextField()),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
                ('entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
