# Generated by Django 2.2.4 on 2019-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
